---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db
  namespace: dev
spec:
  chart:
    spec:
      chart: postgres
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: lfs269
        namespace: dev
      version: '*'
  interval: 9h0m0s
  targetNamespace: dev
  values:
    service:
      name: db
    settings:
      authMethod: trust

