---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vote-stage
  namespace: dev
spec:
  dependsOn:
  - name: redis-stage
  healthChecks:
  - kind: Deployment
    name: vote
    namespace: dev
  interval: 9h0m0s
  path: ./kustomize/vote/stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: vote-deploy
  targetNamespace: dev
  timeout: 2m0s

